name: node-carplay
version: git
summary: Carplay dongle driver for Node.js & Browser
description: |
  Carplay dongle driver for Node.js & Browser
license: MIT
base: core24
grade: stable
confinement: strict
website: https://github.com/rhysmorgan134/node-CarPlay
issues: https://github.com/kz6fittycent/node-CarPlay/issues
source-code: https://github.com/rhysmorgan134/node-CarPlay

apps:
  node-carplay:
    command: bin/node-carplay
    daemon: simple
    plugs:
      - network
      - network-bind
      
parts:
  node-carplay:
    source: https://github.com/rhysmorgan134/node-CarPlay
    source-type: git
    plugin: npm
    npm-node-version: "22.5.1"
        
    build-packages:
      - libudev-dev
      
    stage-packages:
      - libudev-dev

